project: 
  type: website

website: 
  page-navigation: true
  title: 'AGATE' 
  site-url: "https://sfregosi.github.io/agate-public" 
  repo-url: "https://github.com/sfregosi/agate-public"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: 'This page is built with [Quarto](https://quarto.org/).'
    left: '&copy; CC-1.0'
  
  sidebar:
    background: $beaver-orange
    # logo: "https://raw.githubusercontent.com/nmfs-opensci/assets/main/logo/nmfs-opensci-logo3.png"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/sfregosi/agate-public
        text: 'agate-public'

    style: 'docked'
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      # - href: about.qmd
      #   text: About
      - href: get-started.qmd
        text: Get started
      # - href: content/customizing.qmd
      #   text: Customizing
      # - href: content/rendering.qmd
      #   text: Rendering
      # - href: content/rmarkdown.Rmd
      #   text: R Markdown files
      # - href: content/code.qmd
      #   text: Code in your files
      - href: acknowledgements.qmd
        text: Acknowledgements

format:
  html:
    theme:
      light: [theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 4
    link-external-newwindow: true
    embed-resources: true

filters:
  # - include-files.lua
  - quarto

  
